# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.7'

services:
  identity.server:
    container_name: identityserver
    image: id4-identityserver
    build:
      context: .
      dockerfile: IdentityServer/Dockerfile
    ports:
      - 8000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - 'ClientSettings:MvcClient:RedirectUri=http://0.0.0.0:8003/signin-oidc'

  api.one:
    container_name: apione
    image: id4-apione
    build:
      context: .
      dockerfile: ApiOne/Dockerfile
    ports:
      - 8001:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - 'AuthorityHost=http://identity.server'

  api.two:
    container_name: apitwo
    image: id4-apitwo
    build:
      context: .
      dockerfile: ApiTwo/Dockerfile
    ports:
      - 8002:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - 'AuthorityHost=http://identity.server'
      - 'ApiOneHost=http://api.one'

  mvc.client:
    container_name: mvcclient
    image: id4-mvcclient
    build:
      context: .
      dockerfile: MvcClient/Dockerfile
    ports:
      - 8003:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - 'AuthorityHost=http://0.0.0.0:8000'
